// <auto-generated />
using System;
using GereciadorDePatrimonio.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GereciadorDePatrimonio.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GereciadorDePatrimonioContext))]
    partial class GereciadorDePatrimonioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GereciadorDePatrimonio.Domain.Marcas.Models.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("GereciadorDePatrimonio.Domain.Patrimonios.Models.Patrimonio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<Guid>("MarcaId");

                    b.Property<string>("Nome");

                    b.Property<int>("Tombo");

                    b.HasKey("Id");

                    b.ToTable("Patrimonios");
                });
#pragma warning restore 612, 618
        }
    }
}
